name: test

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Build
        run: go build -v .

      - name: Test
        run: go test -v -covermode=count -coverprofile=coverage.out .
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_APP_ID: ${{ secrets.TEST_APP_ID }}
          TEST_COLLECTION_ID: ${{ secrets.TEST_COLLECTION_ID }}

      - name: Create coverage file
        run: |
          go get github.com/mattn/goveralls
          goveralls -repotoken ${{ secrets.COVERALLS_TOKEN }}

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.github_token }}
